# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from hegel import hegel_pb2 as hegel_dot_hegel__pb2


class HegelStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/hegel.Hegel/Get',
                request_serializer=hegel_dot_hegel__pb2.GetRequest.SerializeToString,
                response_deserializer=hegel_dot_hegel__pb2.GetResponse.FromString,
                )
        self.Subscribe = channel.unary_stream(
                '/hegel.Hegel/Subscribe',
                request_serializer=hegel_dot_hegel__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=hegel_dot_hegel__pb2.SubscribeResponse.FromString,
                )


class HegelServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HegelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=hegel_dot_hegel__pb2.GetRequest.FromString,
                    response_serializer=hegel_dot_hegel__pb2.GetResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=hegel_dot_hegel__pb2.SubscribeRequest.FromString,
                    response_serializer=hegel_dot_hegel__pb2.SubscribeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hegel.Hegel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Hegel(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hegel.Hegel/Get',
            hegel_dot_hegel__pb2.GetRequest.SerializeToString,
            hegel_dot_hegel__pb2.GetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/hegel.Hegel/Subscribe',
            hegel_dot_hegel__pb2.SubscribeRequest.SerializeToString,
            hegel_dot_hegel__pb2.SubscribeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
